### ISSUE TITLE
Problem with Resistance.series

### ISSUE THREAD

**Issue by ms440** [jgallen23/markx#2]
First, thanks for the markx module. I'm going to use it heavily.

I ran to a problem though trying to test it on windows machine. Here is what I'm getting:

  res.series([
      ^
TypeError: Object function () {
  if (!(this instanceof Resistance)) {
    return new Resistance();
  }

  this.type = 'series';
  this.flow = [];
} has no method 'series'
    at module.exports (C:...\node_modules\markx\lib\convert.js:46:7)
    at Object.<anonymous> (C:...\node_modules\markx\bin\markx.js:62:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

I'm using node v.0.8.8 and resistance@2.0.0alpha3 was installed automatically by npm install markx.

Any advice would be highly appreciated.

Thanks!

**Comment by jgallen23** [comment]
I just pushed up a 0.1.0alpha5.  Can you try that and see if it fixes your issue?
