### ISSUE TITLE
Crash parsing Markdown file with fenced code blocks

### ISSUE THREAD

**Issue by danielkza** [jgallen23/markx#3]
While trying to input a Markdown file containing github-style fenced code blocks markx crashes. Seems to me after a cursory look at the code that it's caused by the lack of checks for supported highlighting languages. Something like a descriptive error message, or simply giving up on highlighting unknown languages would be helpful additions.

Node.js 0.8.12 on Windows 8 x64:

```
d:\node.js\node_modules\markx\node_modules\highlight.js\highlight.js:158
      if (mode.compiled)
              ^
TypeError: Cannot read property 'compiled' of undefined
    at compileMode (d:\node.js\node_modules\markx\node_modules\highlight.js\high
light.js:158:15)
    at compileLanguage (d:\node.js\node_modules\markx\node_modules\highlight.js\
highlight.js:230:5)
    at highlight (d:\node.js\node_modules\markx\node_modules\highlight.js\highli
ght.js:392:5)
    at Object.module.exports.marked.setOptions.highlight (d:\node.js\node_module
s\markx\lib\converters\markdown.js:29:19)
    at tok (d:\node.js\node_modules\markx\node_modules\marked\lib\marked.js:540:
30)
    at tok (d:\node.js\node_modules\markx\node_modules\marked\lib\marked.js:605:
17)
    at tok (d:\node.js\node_modules\markx\node_modules\marked\lib\marked.js:577:
17)
    at parse (d:\node.js\node_modules\markx\node_modules\marked\lib\marked.js:65
0:12)
    at marked (d:\node.js\node_modules\markx\node_modules\marked\lib\marked.js:7
17:10)
    at module.exports (d:\node.js\node_modules\markx\lib\converters\markdown.js:
35:16)
```

**Comment by jgallen23** [comment]
I just pushed up a brand new version of markx.  Can you see if the error is still happening?

**Comment by JeanMertz** [comment]
Getting the same issue:

```
/usr/local/share/npm/lib/node_modules/markx/node_modules/highlight.js/highlight.js:142
      if (mode.compiled)
              ^
TypeError: Cannot read property 'compiled' of undefined
    at compileMode (/usr/local/share/npm/lib/node_modules/markx/node_modules/highlight.js/highlight.js:142:15)
    at compileLanguage (/usr/local/share/npm/lib/node_modules/markx/node_modules/highlight.js/highlight.js:213:5)
    at highlight (/usr/local/share/npm/lib/node_modules/markx/node_modules/highlight.js/highlight.js:362:5)
    at Object.module.exports.marked.setOptions.highlight (/usr/local/share/npm/lib/node_modules/markx/lib/utils/markdown.js:23:18)
    at tok (/usr/local/share/npm/lib/node_modules/markx/node_modules/marked/lib/marked.js:540:30)
    at parse (/usr/local/share/npm/lib/node_modules/markx/node_modules/marked/lib/marked.js:650:12)
    at marked (/usr/local/share/npm/lib/node_modules/markx/node_modules/marked/lib/marked.js:717:10)
    at module.exports (/usr/local/share/npm/lib/node_modules/markx/lib/utils/markdown.js:30:16)
    at Object.convertMarkdown (/usr/local/share/npm/lib/node_modules/markx/lib/markx.js:60:3)
    at iterate (/usr/local/share/npm/lib/node_modules/markx/node_modules/resistance/lib/series.js:31:20)
```

**Comment by jgallen23** [comment]
Can you post the file you are trying to convert?
